from point import Point

CUBE_BUFFER_RADIUS = 300
TABLE_WALL_BUFFER = 200
TABLE_TOP_RIGHT_WALL = Point(0, 2310)
TABLE_BOTTOM_LEFT_WALL = Point(1110, 0)
TABLE_TOP_RIGHT_BUFFERED_WALL = Point(TABLE_TOP_RIGHT_WALL.x + TABLE_WALL_BUFFER,
                                      TABLE_TOP_RIGHT_WALL.y - TABLE_WALL_BUFFER)
TABLE_BOTTOM_LEFT_BUFFERED_WALL = Point(TABLE_BOTTOM_LEFT_WALL.x - TABLE_WALL_BUFFER,
                                        TABLE_BOTTOM_LEFT_WALL.y + TABLE_WALL_BUFFER)
ATLAS_ZONE_COORDINATES = Point(0, 0)